name: opensg_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - mpi4py
  - meshio
  - petsc4py # 3.15.1
  - yaml
  - contextlib2  # For compatibility
  - pathlib
  - typing-extensions
  - fenics-dolfinx 
  - fenics-basix 
  - fenics-ufl
  - fenics-ffcx
  - mpich 
  - pyvista
  - pyyaml
  - pip
  - pip:
    - -e .
    - gmsh
  # - gmsh # I have to install this through pip for it to work.
